version: "1.0"
info:
  model: int-scaffold
packages:
- name: Mfri_scaffoldingProject
  gitServerName: mfri_git
  gitUrl: https://github.com/MarcFriedhoff/Mfri_scaffoldingProject
  gitUsername: MarcFriedhoff
  gitBranch: main
- name: PetstoreClient20
  gitServerName: mfri_git
  gitUrl: https://github.com/MarcFriedhoff
  gitUsername: MarcFriedhoff
  gitBranch: master
- name: PetstoreClient7
  gitServerName: mfri_git
  gitUrl: https://github.com/MarcFriedhoff
  gitUsername: MarcFriedhoff
  gitBranch: master
